version: '3'

services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opentaxii

  opentaxii:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      OPENTAXII_AUTH_SECRET: secret
      OPENTAXII_DOMAIN: localhost:9000
      OPENTAXII_USER: user
      OPENTAXII_PASS: pass
      DATABASE_HOST: db
      DATABASE_NAME: opentaxii
      DATABASE_USER: user
      DATABASE_PASS: password
      AUTH_DATABASE_HOST: authdb
      AUTH_DATABASE_NAME: opentaxii1
      AUTH_DATABASE_USER: user1
      AUTH_DATABASE_PASS: password1
    volumes:
      - ./:/input:ro
    ports:
      - 9000:9000
    links:
      - db:db
      - authdb:authdb
